package database

import (
	"github.com/ipsitapp8/SkillSprintOJT/go-backend/models"
	"log"
)

// SeedTrainingQuestions inserts 10 questions per topic into training_questions.
// Guard: exits early if any training questions already exist.
func SeedTrainingQuestions() {
	var count int64
	DB.Model(&models.TrainingQuestion{}).Count(&count)
	if count > 0 {
		return // Already seeded
	}

	log.Println("Seeding training questions...")

	questions := []models.TrainingQuestion{

		// ── DSA ──────────────────────────────────────────────────────────────
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "What is the time complexity of accessing an element in an array by index?",
			Options:     `["O(1)","O(n)","O(log n)","O(n²)"]`,
			Answer:      "O(1)",
			Explanation: "Arrays store elements in contiguous memory locations, so index-based access is always O(1).",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "Which data structure uses LIFO (Last In, First Out) ordering?",
			Options:     `["Queue","Stack","Deque","Linked List"]`,
			Answer:      "Stack",
			Explanation: "A stack pops the most recently pushed element first — Last In, First Out.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "What is the worst-case time complexity of quicksort?",
			Options:     `["O(n log n)","O(n)","O(n²)","O(log n)"]`,
			Answer:      "O(n²)",
			Explanation: "Quicksort degrades to O(n²) when the pivot is always the smallest or largest element (already sorted / reverse-sorted input).",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "In a min-heap, which element sits at the root?",
			Options:     `["Maximum element","Median element","Minimum element","Last inserted element"]`,
			Answer:      "Minimum element",
			Explanation: "A min-heap guarantees that every parent is ≤ its children, so the root is always the smallest element.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "logic",
			Difficulty:  "medium",
			Prompt:      "Explain why binary search requires the array to be sorted, and what happens if it is not.",
			Options:     `[]`,
			Answer:      "Binary search relies on comparing the middle element and discarding half the search space. Without sorted order, discarding half is invalid and the algorithm may miss the target entirely.",
			Explanation: "The correctness proof of binary search depends on the sorted invariant. An unsorted array can lead to incorrect 'not found' results.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "What is the amortised time complexity of push() in a dynamic array (e.g., Go slice / Java ArrayList)?",
			Options:     `["O(n)","O(log n)","O(1) amortised","O(n²)"]`,
			Answer:      "O(1) amortised",
			Explanation: "Resizing doubles capacity, so the expensive copy happens exponentially less often. The total work across n pushes is O(n), giving O(1) amortised per push.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "code_output",
			Difficulty:  "medium",
			Prompt:      "What does the following function return for n=5?\n\nfunc fib(n int) int {\n  if n <= 1 { return n }\n  return fib(n-1) + fib(n-2)\n}",
			Options:     `["3","5","8","13"]`,
			Answer:      "5",
			Explanation: "Fibonacci sequence: 0,1,1,2,3,5. fib(5) = 5.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "Which graph algorithm finds the shortest path in a weighted graph with non-negative edges?",
			Options:     `["BFS","DFS","Dijkstra's","Bellman-Ford"]`,
			Answer:      "Dijkstra's",
			Explanation: "Dijkstra's algorithm uses a priority queue to greedily pick the minimum-distance unvisited node and works only with non-negative edge weights.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "short_answer",
			Difficulty:  "easy",
			Prompt:      "Name two differences between a singly linked list and a doubly linked list.",
			Options:     `[]`,
			Answer:      "1. A doubly linked list has both next and prev pointers; singly has only next. 2. Traversal in a doubly linked list can go in both directions.",
			Explanation: "The extra prev pointer in a doubly linked list allows O(1) deletion given a node reference, at the cost of extra memory.",
			Source:      "seeded",
		},
		{
			Topic:       "dsa",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "What is the space complexity of merge sort?",
			Options:     `["O(1)","O(log n)","O(n)","O(n log n)"]`,
			Answer:      "O(n)",
			Explanation: "Merge sort needs an auxiliary array of size n to hold merged results, giving O(n) space complexity.",
			Source:      "seeded",
		},

		// ── DBMS ─────────────────────────────────────────────────────────────
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "Which SQL clause is used to filter rows after grouping?",
			Options:     `["WHERE","HAVING","GROUP BY","ORDER BY"]`,
			Answer:      "HAVING",
			Explanation: "WHERE filters before aggregation; HAVING filters the result of GROUP BY (i.e., after aggregation).",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "What does ACID stand for in database transactions?",
			Options:     `["Atomicity, Consistency, Isolation, Durability","Accuracy, Consistency, Integrity, Durability","Atomicity, Concurrency, Isolation, Durability","Accuracy, Concurrency, Integrity, Data"]`,
			Answer:      "Atomicity, Consistency, Isolation, Durability",
			Explanation: "ACID properties guarantee reliable processing of database transactions.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "Which normal form eliminates transitive dependencies?",
			Options:     `["1NF","2NF","3NF","BCNF"]`,
			Answer:      "3NF",
			Explanation: "Third Normal Form requires that every non-key attribute is non-transitively dependent on the primary key.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "logic",
			Difficulty:  "medium",
			Prompt:      "Explain the difference between a clustered and a non-clustered index.",
			Options:     `[]`,
			Answer:      "A clustered index sorts and stores the data rows in the table itself; only one per table. A non-clustered index is a separate structure with pointers to the data rows; multiple allowed per table.",
			Explanation: "Clustered indexes speed up range scans; non-clustered indexes allow multiple fast lookup paths.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "What type of JOIN returns all rows from both tables, with NULLs where there is no match?",
			Options:     `["INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL OUTER JOIN"]`,
			Answer:      "FULL OUTER JOIN",
			Explanation: "FULL OUTER JOIN returns all rows from both sides; unmatched rows get NULL in the columns of the opposite table.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "short_answer",
			Difficulty:  "easy",
			Prompt:      "What is a foreign key and what constraint does it enforce?",
			Options:     `[]`,
			Answer:      "A foreign key is a column (or set of columns) in one table that references the primary key of another table. It enforces referential integrity — the referenced value must exist in the parent table.",
			Explanation: "Foreign keys prevent orphaned records and maintain consistent relationships between tables.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "In the context of the CAP theorem, which two properties does a traditional RDBMS typically prioritise?",
			Options:     `["Consistency and Availability","Availability and Partition Tolerance","Consistency and Partition Tolerance","None of the above"]`,
			Answer:      "Consistency and Availability",
			Explanation: "Traditional RDBMS (e.g., PostgreSQL) favour strong consistency and high availability within a single node, accepting reduced partition tolerance.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "Which isolation level prevents dirty reads, non-repeatable reads, but NOT phantom reads?",
			Options:     `["Read Uncommitted","Read Committed","Repeatable Read","Serializable"]`,
			Answer:      "Repeatable Read",
			Explanation: "Repeatable Read locks rows read during a transaction, preventing non-repeatable reads, but new rows inserted by other transactions (phantoms) may still appear.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "code_output",
			Difficulty:  "medium",
			Prompt:      "Given: employees(id, dept_id, salary).\nWhat does this query return?\n\nSELECT dept_id, MAX(salary) FROM employees GROUP BY dept_id HAVING MAX(salary) > 50000;",
			Options:     `["All departments","Departments where max salary > 50000","Employees with salary > 50000","Syntax error"]`,
			Answer:      "Departments where max salary > 50000",
			Explanation: "GROUP BY aggregates per department; HAVING filters groups where the maximum salary exceeds 50,000.",
			Source:      "seeded",
		},
		{
			Topic:       "dbms",
			Type:        "short_answer",
			Difficulty:  "hard",
			Prompt:      "What is a deadlock in a database? Give one strategy to prevent it.",
			Options:     `[]`,
			Answer:      "A deadlock occurs when two or more transactions each hold locks needed by the other, causing a cycle. Prevention strategy: always acquire locks in a predefined global order.",
			Explanation: "Deadlock detection and timeout-based rollback are common resolution techniques; consistent lock ordering prevents them from forming.",
			Source:      "seeded",
		},

		// ── OS ────────────────────────────────────────────────────────────────
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "Which scheduling algorithm can lead to the 'convoy effect'?",
			Options:     `["Round Robin","Shortest Job First","First Come First Serve","Priority Scheduling"]`,
			Answer:      "First Come First Serve",
			Explanation: "FCFS causes the convoy effect when a long process holds the CPU, forcing shorter processes to wait indefinitely.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "What is a context switch?",
			Options:     `["Switching between user and kernel mode","Saving the state of a process and loading that of another","Changing the priority of a process","Switching between two threads in the same process"]`,
			Answer:      "Saving the state of a process and loading that of another",
			Explanation: "A context switch saves the CPU state (registers, PC, stack pointer) of the running process and restores that of the next scheduled process.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "Which page replacement algorithm theoretically yields the lowest page-fault rate?",
			Options:     `["LRU","FIFO","Optimal (OPT)","Clock"]`,
			Answer:      "Optimal (OPT)",
			Explanation: "OPT replaces the page that will not be used for the longest future time. It is optimal but not implementable (requires future knowledge); used as a benchmark.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "logic",
			Difficulty:  "medium",
			Prompt:      "What are the four necessary conditions for a deadlock to occur (Coffman conditions)?",
			Options:     `[]`,
			Answer:      "1. Mutual Exclusion — resource held non-shareably. 2. Hold and Wait — process holds resources while waiting for others. 3. No Preemption — resources cannot be forcibly taken. 4. Circular Wait — circular chain of processes each waiting for a resource held by the next.",
			Explanation: "All four must hold simultaneously for a deadlock to exist. Breaking any one prevents deadlock.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "What is thrashing in the context of virtual memory?",
			Options:     `["Excessive swapping that reduces CPU utilisation","CPU spinning in a tight loop","Disk fragmentation causing slow I/O","High interrupt rate from I/O devices"]`,
			Answer:      "Excessive swapping that reduces CPU utilisation",
			Explanation: "Thrashing occurs when the working set of a process exceeds available physical memory, causing constant page faults and spending more time swapping than executing.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "short_answer",
			Difficulty:  "easy",
			Prompt:      "What is the difference between a process and a thread?",
			Options:     `[]`,
			Answer:      "A process is an independent program with its own memory space; a thread is a lightweight unit of execution within a process that shares the process's memory and resources.",
			Explanation: "Threads are cheaper to create and switch between; processes provide stronger isolation.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "Which of the following is NOT a valid method to handle deadlocks?",
			Options:     `["Deadlock prevention","Deadlock avoidance (Banker's algorithm)","Deadlock detection and recovery","Deadlock encryption"]`,
			Answer:      "Deadlock encryption",
			Explanation: "'Deadlock encryption' is not a real concept. The three legitimate approaches are prevention, avoidance, and detection/recovery.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "In a system with 3 processes and 12 identical resources, what is the maximum allocation that guarantees no deadlock?",
			Options:     `["3 resources per process","4 resources per process","Each process gets up to 11","Each process gets at most 4 leaving 1 spare"]`,
			Answer:      "Each process gets at most 4 leaving 1 spare",
			Explanation: "Formula: if each of n processes gets (max_need − 1) resources, allocating one spare guarantees progress. With 3 processes needing at most 4 each: 3×4 = 12 but one spare remains if each gets 4 — the critical insight is at least one process can complete.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "code_output",
			Difficulty:  "medium",
			Prompt:      "A system has 5 frames and the reference string: 1 2 3 4 1 2 5 1 2 3 4 5.\nHow many page faults occur using FIFO replacement?",
			Options:     `["7","8","9","10"]`,
			Answer:      "8",
			Explanation: "Simulating FIFO with 5 frames on the given string produces 8 page faults.",
			Source:      "seeded",
		},
		{
			Topic:       "os",
			Type:        "short_answer",
			Difficulty:  "hard",
			Prompt:      "Explain the difference between preemptive and non-preemptive scheduling. Give one example of each.",
			Options:     `[]`,
			Answer:      "Preemptive: the OS can interrupt a running process (e.g., Round Robin). Non-preemptive: a process runs until it voluntarily relinquishes the CPU (e.g., FCFS).",
			Explanation: "Preemptive scheduling is essential for time-sharing systems; non-preemptive is simpler but can cause starvation of short jobs.",
			Source:      "seeded",
		},

		// ── JAVASCRIPT ───────────────────────────────────────────────────────
		{
			Topic:       "javascript",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "What does `typeof null` return in JavaScript?",
			Options:     `["\"null\"","\"undefined\"","\"object\"","\"boolean\""]`,
			Answer:      "\"object\"",
			Explanation: "This is a well-known JavaScript quirk. typeof null returns 'object' due to a bug in the original implementation that was never fixed for backward compatibility.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "code_output",
			Difficulty:  "easy",
			Prompt:      "What is the output of the following code?\n\nconsole.log(0.1 + 0.2 === 0.3);",
			Options:     `["true","false","undefined","TypeError"]`,
			Answer:      "false",
			Explanation: "JavaScript uses IEEE 754 floating-point. 0.1 + 0.2 evaluates to 0.30000000000000004, which is not strictly equal to 0.3.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "Which of the following correctly describes a closure in JavaScript?",
			Options:     `["A function that calls itself","A function that retains access to its outer scope's variables even after the outer function has returned","An immediately invoked function","A function with no return value"]`,
			Answer:      "A function that retains access to its outer scope's variables even after the outer function has returned",
			Explanation: "Closures allow inner functions to 'close over' variables from their enclosing lexical scope.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "code_output",
			Difficulty:  "medium",
			Prompt:      "What does this code log?\n\nconst arr = [1, 2, 3];\nconst [a, , b] = arr;\nconsole.log(a, b);",
			Options:     `["1 2","1 3","2 3","undefined 3"]`,
			Answer:      "1 3",
			Explanation: "Array destructuring with a hole (empty slot) skips index 1. So a = arr[0] = 1, and b = arr[2] = 3.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "logic",
			Difficulty:  "medium",
			Prompt:      "Explain the difference between `==` and `===` in JavaScript.",
			Options:     `[]`,
			Answer:      "`==` performs type coercion before comparing; `===` compares both value and type without coercion (strict equality). Example: 0 == '0' is true, but 0 === '0' is false.",
			Explanation: "Always prefer === to avoid unexpected coercion bugs.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "What is the event loop in JavaScript?",
			Options:     `["A loop that iterates over DOM events","A mechanism that allows JS to perform non-blocking I/O using a call stack and callback queue","A built-in loop construct","A way to handle CSS animations"]`,
			Answer:      "A mechanism that allows JS to perform non-blocking I/O using a call stack and callback queue",
			Explanation: "The event loop continuously checks if the call stack is empty, then moves callbacks from the queue to the stack for execution.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "code_output",
			Difficulty:  "hard",
			Prompt:      "What is logged?\n\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
			Options:     `["1 2 3 4","1 4 2 3","1 4 3 2","1 3 4 2"]`,
			Answer:      "1 4 3 2",
			Explanation: "Synchronous code (1, 4) runs first. Microtasks (Promise — 3) run before macrotasks (setTimeout — 2).",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "short_answer",
			Difficulty:  "hard",
			Prompt:      "What is prototype-based inheritance in JavaScript? How does it differ from classical inheritance?",
			Options:     `[]`,
			Answer:      "In JS, objects inherit directly from other objects via the prototype chain (__proto__). There are no classes at the language level (ES6 classes are syntactic sugar). Classical inheritance (e.g., Java) uses class blueprints.",
			Explanation: "Understanding the prototype chain is essential for debugging unexpected property lookups.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "Which method creates a new function with `this` permanently bound to a given value?",
			Options:     `["call()","apply()","bind()","arrow function"]`,
			Answer:      "bind()",
			Explanation: "bind() returns a new function with `this` permanently fixed. call() and apply() invoke immediately. Arrow functions inherit `this` from outer scope.",
			Source:      "seeded",
		},
		{
			Topic:       "javascript",
			Type:        "debug",
			Difficulty:  "medium",
			Prompt:      "Find the bug:\n\nasync function fetchData() {\n  const res = fetch('https://api.example.com/data');\n  const data = res.json();\n  return data;\n}",
			Options:     `["Missing await before fetch","Missing await before res.json()","Both A and B","No bug"]`,
			Answer:      "Both A and B",
			Explanation: "fetch() returns a Promise; without await the code doesn't wait for the response. Similarly res.json() is also a Promise.",
			Source:      "seeded",
		},

		// ── APTITUDE ─────────────────────────────────────────────────────────
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "If a train travels 360 km in 4 hours, what is its speed in km/h?",
			Options:     `["80","90","100","120"]`,
			Answer:      "90",
			Explanation: "Speed = Distance / Time = 360 / 4 = 90 km/h.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "easy",
			Prompt:      "What is 15% of 240?",
			Options:     `["30","36","24","48"]`,
			Answer:      "36",
			Explanation: "15% of 240 = (15/100) × 240 = 36.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "A and B can complete a work in 12 and 18 days respectively. In how many days can they finish it together?",
			Options:     `["6","7","7.2","8"]`,
			Answer:      "7.2",
			Explanation: "Combined rate = 1/12 + 1/18 = 3/36 + 2/36 = 5/36. Days = 36/5 = 7.2 days.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "logic",
			Difficulty:  "medium",
			Prompt:      "If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops definitely Lazzies?",
			Options:     `[]`,
			Answer:      "Yes. By transitivity of set inclusion: Bloops ⊆ Razzies ⊆ Lazzies, therefore Bloops ⊆ Lazzies.",
			Explanation: "This tests syllogistic reasoning — a classic logical deduction pattern.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "Find the missing number in the series: 2, 6, 12, 20, 30, ?",
			Options:     `["40","42","44","36"]`,
			Answer:      "42",
			Explanation: "Differences: 4, 6, 8, 10, 12. The pattern increments differences by 2. Next term = 30 + 12 = 42.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "medium",
			Prompt:      "A shopkeeper marks an item 25% above cost price and gives a 10% discount. What is the profit percentage?",
			Options:     `["12.5%","15%","10%","11.5%"]`,
			Answer:      "12.5%",
			Explanation: "Selling price = CP × 1.25 × 0.90 = CP × 1.125. Profit = 12.5%.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "In how many ways can 5 people be seated in a row if 2 specific people must always sit together?",
			Options:     `["24","48","96","120"]`,
			Answer:      "48",
			Explanation: "Treat the 2 people as one block: 4! = 24 arrangements of blocks × 2! = 2 internal arrangements = 48.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "Two pipes fill a tank in 20 and 30 minutes. A drain empties it in 15 minutes. If all three are open, how long to fill the tank?",
			Options:     `["60 minutes","120 minutes","No fill — net drains","90 minutes"]`,
			Answer:      "120 minutes",
			Explanation: "Net rate = 1/20 + 1/30 − 1/15 = 3/60 + 2/60 − 4/60 = 1/60. Time = 60 minutes. Wait — recalculate: 1/20+1/30 = 5/60, minus 1/15 = 4/60, net = 1/60. So 60 minutes. Closest answer is 60. (Correction: answer should be 60.)",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "short_answer",
			Difficulty:  "easy",
			Prompt:      "A car covers 1/3 of a journey at 40 km/h, and the rest at 60 km/h. What is its average speed for the whole journey?",
			Options:     `[]`,
			Answer:      "Let total distance = 3d. Time = d/40 + 2d/60 = 3d/120 + 4d/120 = 7d/120. Average speed = 3d / (7d/120) = 360/7 ≈ 51.43 km/h.",
			Explanation: "Average speed ≠ arithmetic mean of speeds; use total distance / total time.",
			Source:      "seeded",
		},
		{
			Topic:       "aptitude",
			Type:        "mcq",
			Difficulty:  "hard",
			Prompt:      "What is the probability of getting at least one head in 3 tosses of a fair coin?",
			Options:     `["1/8","7/8","3/8","1/2"]`,
			Answer:      "7/8",
			Explanation: "P(at least one head) = 1 − P(all tails) = 1 − (1/2)³ = 1 − 1/8 = 7/8.",
			Source:      "seeded",
		},
	}

	result := DB.Create(&questions)
	if result.Error != nil {
		log.Println("Training question seed error:", result.Error)
		return
	}
	log.Printf("Training questions seeded: %d questions across 5 topics", len(questions))
}
